### ISSUE TITLE
Info: Matter Compiler

### ISSUE THREAD

**Issue by zdne** [calderalabs/rspec_api_blueprint#10]
For what it's worth I just wanted to let you know that I have finished a gem that converts [AST](https://github.com/apiaryio/matter_compiler/blob/master/lib/matter_compiler/blueprint.rb#L511) and [AST serialization media types](https://github.com/apiaryio/api-blueprint-ast) into the API Blueprint format – [Matter Compiler](https://github.com/apiaryio/matter_compiler). 

You can feed it with a JSON, YAML or in your case directly build the [AST at runtime](https://github.com/apiaryio/matter_compiler/blob/master/lib/matter_compiler/blueprint.rb#L511) and then just call `Blueprint.serialize` to get the formatted API Blueprint Markdown. 

Using the `Matter Compiler` would essentially nullify the need for `Rspec Api Blueprint` to understand the API Blueprint syntax, it would only need to build its AST.

**Comment by matteodepalo** [comment]
That's amazing! Thanks for letting me know, I'll try and work on an integration as soon as I have some spare time.

**Comment by zdne** [comment]
No worries, just wanted to inform you about this. Using the Blueprint class directly might save some development time in the future and will ensure consistency amongst generated blueprints.
