### ISSUE TITLE
@controller is nil

### ISSUE THREAD

**Issue by cvortmann** [calderalabs/rspec_api_blueprint#11]
I have model's controller in the path app/controller/v1/models_controller.rb and setup my tests as:
describe "Models Requests" do
  describe 'POST /v1/model' do
  end
end

When I run bundle exec rspec

I receive a RuntimeError:@controller is nil: make sure you set it in your test's setup method.

**Comment by matteodepalo** [comment]
Hi @cvortmann, I'm having troubles reproducing this issue. Does it present itself on a new Rails project with just the rspec_api_blueprint gem? There is no reference to `@controller` in the code so I'm wondering if the issue is caused by some other gem.

**Comment by cvortmann** [comment]
Yes, is a new rails project with only rspec-rails and rspec_api_blueprint.
When you create your spec using 'describe ModelsController do' it automatically set the instance variable @controller to the class you're testing.

**Comment by cvortmann** [comment]
I guess this problem is due to Rspec version. I'm using Rspec 3.

**Comment by matteodepalo** [comment]
Are your tests placed into the `spec/requests` folder? If you place them into `spec/controllers` it won't work.

**Comment by cvortmann** [comment]
They are in spec/controllers. I'll change and test it. Can you please add
that to the documentation?

**Comment by matteodepalo** [comment]
Of course! :)

**Comment by cvortmann** [comment]
Didn't work. I had to change get :index for get v1_models_path because it
could find URI and then it could find the class example from Rspec.

**Comment by matteodepalo** [comment]
Yes that is because in request specs you have access to different methods than in controller specs, so stuff like `get :index` or `post :create` don't work

**Comment by cvortmann** [comment]
Yes, but that's fine. The problem is that the example does not exist in
Rspec 3.
