### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by kurko** [calderalabs/rspec_api_blueprint#14]
Hey @matteodepalo, is this gem still maintained? If you're not using it anymore, can you maybe provide someone admin rights so issues/PRs don't stale? There are things from 2013 here.

I need this for my project and I'd love to see this moving forward.

**Comment by matteodepalo** [comment]
Hey @kurko,
I don't have time to maintain this gem anymore but collaborators are more than welcome! Would you be willing to work on it as an admin?

**Comment by kurko** [comment]
Yes, as collaborator.

**Comment by matteodepalo** [comment]
It's done!
